<html>
    <head>
<title> рыблокс ньюс </title>
<link rel="stylesheet" href="style.css">
    </head>
<body>
<header>
    <img src="https://media-exp1.licdn.com/dms/image/C560BAQGF9ES-xE207Q/company-logo_200_200/0/1562605695701?e=2159024400&v=beta&t=yvdbOh-2nAgM8zgZ4Dzpnba45GxenV7pFZWTxhLIlaQ"> 
</header>
<nav>
    <a href="#MM2"> Murder Mystery 2 </a>
    <a href="#AUR"> Among us Roblox </a>
    <a href="#KAT"> KAT </a>
</nav>
<main>
<h1> Популярные из роблокс: убийца </h1>
<h2 id="MM2"> Murder Mystery 2 </h2>
<p>Это игра где ты должен <br> Убийца: Ты должен убить всех мирных тихо и бесшумно ведь ты можешь привлечь к себе шерифа <br> Шериф: Ты должен найти и убить убийцу но не показывай своё оружие  ведь среди мирных может прятаться убийца <br> Мирные:Ты должен вести себя тихо и не пересекаться не с кем ведь среди них может прятаться убийца если ты нашёл пистолет тебе переходят обязаннасти шерифа </p>
<h2 id="AUR"> Амонг ас роблокс</h2>
<p> В этой игре всего две роли в первой(невиновный) ты должен выполнять всякие задание  и в дискусиях находить убийцу.<br> Во второй  же всё наоборот ты должен убить всех и не спалиться.</p>
<h2 id="KAT"> Кэт </h2>
<p>Это игра в стиле мясорубка тут ты должен просто переубивать всё и вся но осторожно твои враги могут бесконечно воскришаться и украсть у тебя твою пальму лидерства.</p>
<table>
    <tr> 
        
        <td> NAME </td>
        <td> LIKES </td>
        <td> PEOLES</td>
    </tr>
<tr>
    <td> Murder Mystery 2 </td>
    <td> 92% </td>
    <td> 76.1K </td>
</tr>
<tr>
    <td> Among us Roblox </td>
    <td> 68% </td>
    <td> 64.3K </td>
</tr>
<tr>
    <td> KAT </td>
    <td> 76% </td>
    <td> 58K </td>
</tr>
</table>        
</main>
<footer> 
<p> контакты: + 7 (654) 44-39-0</p>
</footer>
</body>
</html>
